spring.application.name=RevShop_P2

server.port=9090

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=revshop2
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
logging.level.org.hibernate.dialect.Dialect=ERROR
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
